/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Agile',
      items: [
        'agile/agile-manifesto',
        'agile/agile-principles',
        {
          type: 'category',
          label: 'Scrum',
          items: [
            'agile/scrum/scrum-guide',
            'agile/scrum/scrum-glossary',
            'agile/scrum/scrum-resume'
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Databases',
      items: [
        {
          type: 'category',
          label: 'Mongo',
          items: [
            'databases/mongo/mongo_high-level-management',
          ],
        },
        {
          type: 'category',
          label: 'Postgres',
          items: [
            'databases/postgres/basic-queries',
            'databases/postgres/high-level-management',
            'databases/postgres/naming-conventions',
            'databases/postgres/postgres_high-level-management'
          ],
        }
      ],
    },
    {
      type: 'category',
      label: 'Git based version control',
      items: [
        'git-based-version-control/commit-message-guidelines',
        {
          type: 'category',
          label: 'Issue templates',
          items: [
            'git-based-version-control/issue-templates/bug-template',
            'git-based-version-control/issue-templates/chore-template',
            'git-based-version-control/issue-templates/documentation-template',
            'git-based-version-control/issue-templates/feature-template',
            'git-based-version-control/issue-templates/test-template',
          ],
        },
        {
          type: 'category',
          label: 'Pull request templates',
          items: [
            'git-based-version-control/pull-request-templates/pull-request-template'
          ],
        }
      ],
    },
    {
      type: 'category',
      label: 'node.js',
      items: [
        {
          type: 'category',
          label: 'comments',
          items: [
            'node-js/comments/code-documentation',
            'node-js/comments/type-signatures',
          ],
        },
        {
          type: 'category',
          label: 'documentation',
          items: [
            'node-js/documentation/document-modules',
          ],
        },
        {
          type: 'category',
          label: 'Project structure',
          items: [
            'node-js/project-structure/structure-by-components',
            'node-js/project-structure/structure-by-features',
          ],
        },
        {
          type: 'category',
          label: 'Testing',
          items: [
            'node-js/testing/tests-with-jest'
          ],
        },
      ],
    },
    // {
    //   type: 'category',
    //   label: 'node-js',
    //   items: ['intro'],
    // },
    // {
    //   type: 'category',
    //   label: 'Tech Stack',
    //   items: ['intro'],
    // },
  ],

};

module.exports = sidebars;
